chore: 🤖 調整 husky pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,11 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+echo "🔧 Biome formatting..."
+npm run format || true  # ignore formatting errors, enter next step
+ 
+echo "🛠  Biome fixing..." # if any formatting errors, this step will fail
 npm run lint
+
+echo "📦 Git add fixed files..."
+git add .
